on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 * * * *'

jobs:
  waka:
    name: Wakatime Stats
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LINES_OF_CODE: True
                
                  
